### PR TITLE
Walkie Talkie DRAFT

### PR DESCRIPTION
**Pull request by pschatzmann**
I converted this project into an Arduino library and added some test sketches: I noticed the following
- I think the dout and din pins in the drawing are switched. It was wroking only when I connected data_out_num to  14 and data_in_num to 11.
- The output to AUDIO_HAL_ADC_INPUT_LINE2 with and w/o amp is working quite nicley
- When I read from  AUDIO_HAL_ADC_INPUT_LINE1 with e.g. sketches audiokit-csv.ino or audiokit-audiokit.ino I get a lot of noise. I am not sure what can be done against this.

This is a recording of a sine tone. I thnk the voltage jumps are reflecting this issue:
image

### CODE REVIEW

**Comment by immortal-sniper1** [comment]
1 I think the dout and din pins in the drawing are switched. It was working only when I connected data_out_num to 14 and data_in_num to 11.  Yes and not IF you look from the perspective of the codec then it is correct this is a orientation thing and a communication problem/ mistake 
BTW next time please tell me it is ESP32_GPIO11 or something like that since i thought you meant physical pin 11 on a certain IC 

2 nice !

3 When I read from AUDIO_HAL_ADC_INPUT_LINE1 with e.g. sketches audiokit-csv.ino or audiokit-audiokit.ino I get a lot of noise. I am not sure what can be done against this. 
Firstly was that signal supposed to be 0 centered? 
Also what was supposed the be in input amplitude? 
Not sure if it is from the RF module or the pot + potentially the cap is not large enough or it is to large , in terms of routeing it is done as well as it could be . Also was the SMPS on or off ?

**Comment by pschatzmann** [comment]
Yes, I would expect it to be centered. 
Not sure what the input amplitude would be: I just connected my earphones from a mobile phone and recorded a sine tone.
I currently don't have any RF module soldered on the board.
The amplifier pins have not been configured and used in that sketch. 
Looking at the wave forms, I would also tend to think that some caps might be messing with the signal.

If you think this is worth the effort I could try to record a sine tone coming from my PC, this should give an input with higher voltage.

**Comment by pschatzmann** [comment]
https://dl.radxa.com/rock2/docs/hw/ds/ES8388%20user%20Guide.pdf
Which setup did you use: chapter 7.2, 7.3 or 7.4 ?

**Comment by immortal-sniper1** [comment]
> 

i was referring to the SMPS used to charge LiFePO4 cells was that on or off?
regarding the phone stuff not sure , did you also connect the gnd to gnd? maybe the long wire in air was acting like an antenna and picking up noise.
regarding the caps yea not sure if it is the size or type to blame or both

**Comment by immortal-sniper1** [comment]
> https://dl.radxa.com/rock2/docs/hw/ds/ES8388%20user%20Guide.pdf Which setup did you use: chapter 7.2, 7.3 or 7.4 ?

7.2 Single-ended Microphone input

**Comment by immortal-sniper1** [comment]
that is only on the audio jack in

**Comment by pschatzmann** [comment]
I don't have any LiFePo4 cells, so I only use it toghether with USB.
Chapter 7.2 contains the recommended cap values und wirings...

**Comment by immortal-sniper1** [comment]
> I don't have any LiFePo4 cells, so I only use it toghether with USB. Chapter 7.2 contains the recommended cap values und wirings...

THE cell charger can be on even IF there is no cell but it should be ok anyway 
regarding the cap i used x10 more not sure IF it is a problem or not i need to research this a bit more

**Comment by immortal-sniper1** [comment]
ps maybe i need some extra pull downs tho there was no recommendation for that

**Comment by pschatzmann** [comment]
Out of curiosity: would you know what the proposed logic using the R6,R7,C12,C13 to AVDD in 7.2 Single-ended Microphone input is exactly doing ?

**Comment by immortal-sniper1** [comment]
R6 is a pull up for the boot pin
r7 grounding for the USB shield (so it is not tied to gnd directly 
c12 C13 decoupling for the buck that charges the cell
ALSO they are not tied to AVDD but there is probably a low ish impedance path to it 
IF you meant to ask acout the caps near AVDD they are decoupling caps as the reference designs dictated

**Comment by pschatzmann** [comment]
I was referring to the recommended diagram on chapter 7.2 Single-ended in the ES8388 User Guide

**Comment by immortal-sniper1** [comment]
R34 is the 7.2 R7
the R6 C12/13 filter in the example was replaced with a CLC filter with C25 29 and L3

**Comment by immortal-sniper1** [comment]
can u read this? @pschatzmann

**Pull request merged**
